/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package project.sm;

import java.awt.List;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ComboBoxModel;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JComboBox;
import javax.swing.JOptionPane;
import static project.sm.Passerelle.donnerFonction;
import static project.sm.Passerelle.donnerServices;

/**
 *
 * @author WQ59
 */
public class ModifierUser extends javax.swing.JFrame {

    /**
     * Creates new form AjouterProduit
     */
    public ModifierUser() {
        initComponents();
        message.setEnabled(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        idUser = new javax.swing.JTextField();
        nom = new javax.swing.JTextField();
        mdpUser = new javax.swing.JTextField();
        emailUser = new javax.swing.JTextField();
        btnValider = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        message = new javax.swing.JTextField();
        btnModifier = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        btnQuitter = new javax.swing.JButton();
        jLabelService = new javax.swing.JLabel();
        fonctionUser = new javax.swing.JComboBox<>();
        btnService = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        idUser.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        idUser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                idUserActionPerformed(evt);
            }
        });

        nom.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        nom.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nomActionPerformed(evt);
            }
        });

        mdpUser.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        emailUser.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        btnValider.setBackground(new java.awt.Color(50, 188, 46));
        btnValider.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnValider.setText("VALIDER");
        btnValider.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnValiderMouseClicked(evt);
            }
        });
        btnValider.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnValiderActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel2.setText("Id");

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel3.setText("Fonction");

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel4.setText("Nom");

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel5.setText("Email");

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel6.setText("Mot de passe");

        message.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        message.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                messageActionPerformed(evt);
            }
        });

        btnModifier.setBackground(new java.awt.Color(210, 160, 47));
        btnModifier.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnModifier.setText("MODIFIER");
        btnModifier.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnModifierMouseClicked(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel7.setText("Saisir l'id à modifier");

        jPanel2.setBackground(new java.awt.Color(51, 153, 255));
        jPanel2.setForeground(new java.awt.Color(255, 255, 255));

        jLabel1.setFont(new java.awt.Font("Gadugi", 0, 24)); // NOI18N
        jLabel1.setText("Modifier un utilisateur");

        btnQuitter.setBackground(new java.awt.Color(255, 0, 0));
        btnQuitter.setText("QUITTER");
        btnQuitter.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnQuitterMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(213, 213, 213)
                .addComponent(jLabel1)
                .addContainerGap(252, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(btnQuitter))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(btnQuitter)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel1)
                .addGap(0, 36, Short.MAX_VALUE))
        );

        jLabelService.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabelService.setText("Service");
        jLabelService.setFocusable(false);

        fonctionUser.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        fonctionUser.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                fonctionUserItemStateChanged(evt);
            }
        });
        fonctionUser.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                fonctionUserFocusLost(evt);
            }
        });
        fonctionUser.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                fonctionUserMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                fonctionUserMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                fonctionUserMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                fonctionUserMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                fonctionUserMouseReleased(evt);
            }
        });
        fonctionUser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fonctionUserActionPerformed(evt);
            }
        });
        fonctionUser.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                fonctionUserPropertyChange(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(65, 65, 65)
                        .addComponent(message, javax.swing.GroupLayout.PREFERRED_SIZE, 397, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel7)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(21, 21, 21)
                                        .addComponent(idUser, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(94, 94, 94)
                                .addComponent(btnValider))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(188, 188, 188)
                                .addComponent(btnModifier))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel6)
                                    .addComponent(jLabel5)
                                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabelService))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(mdpUser, javax.swing.GroupLayout.PREFERRED_SIZE, 339, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(emailUser, javax.swing.GroupLayout.PREFERRED_SIZE, 339, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(nom, javax.swing.GroupLayout.PREFERRED_SIZE, 339, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(fonctionUser, javax.swing.GroupLayout.PREFERRED_SIZE, 339, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(btnService, javax.swing.GroupLayout.PREFERRED_SIZE, 339, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                .addGap(241, 241, 241))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel7)
                .addGap(8, 8, 8)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(idUser, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnValider))
                .addGap(33, 33, 33)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(nom, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(emailUser, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(mdpUser, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(fonctionUser, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelService)
                    .addComponent(btnService, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnModifier)
                .addGap(18, 18, 18)
                .addComponent(message, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(43, 43, 43))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnValiderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnValiderActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnValiderActionPerformed

    private void nomActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nomActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nomActionPerformed

    private void idUserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_idUserActionPerformed
        
    }//GEN-LAST:event_idUserActionPerformed

    private void btnValiderMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnValiderMouseClicked

        try {
            int id = Integer.parseInt(idUser.getText());
            Utilisateur unUtilisateur = Passerelle.donneUserId(id);
            fonctionUser.removeAllItems();
            btnService.removeAllItems();
            if(unUtilisateur == null){
                nom.setText(null);
                mdpUser.setText(null);
                emailUser.setText(null);
                fonctionUser.setName(null);
                message.setText("Le produit "+id+" n'existe pas");
            }else {
                nom.setText(unUtilisateur.getLibelle());
                mdpUser.setText(String.valueOf(unUtilisateur.getMdp()));
                emailUser.setText(String.valueOf(unUtilisateur.getEmail()));
                //String labels[] = { "Admin", "Infirmier", "Pharmacien" };
                //ComboBoxModel<Object> aModel =  new DefaultComboBoxModel(labels);
                ArrayList<Service> desServices = new ArrayList<Service>();
                desServices = Passerelle.donnerServices();
                ArrayList<Fonction> desFonctions = new ArrayList<Fonction>();
                desFonctions = Passerelle.donnerFonction();             
                for(Fonction uneFonction : desFonctions){
                    fonctionUser.addItem(uneFonction.getLibelle());
                }               
                //java.util.List<Service> list=new java.util.ArrayList<Service>();
                for(Service unService : desServices){
                    btnService.addItem(unService.getLibelle());
                }
                //jComboBox2.setModel());
                if(unUtilisateur.getIdfonction()==1){
                    fonctionUser.setSelectedIndex(0);
                    btnService.setEnabled(false);
                    btnService.setSelectedIndex(-1);
                }else if(unUtilisateur.getIdfonction()==2){
                    fonctionUser.setSelectedIndex(1);
                    btnService.setEnabled(true);                   
                }
                if(unUtilisateur.getIdservice()==1){
                    btnService.setSelectedIndex(0);
                }else if(unUtilisateur.getIdservice()==2){
                    btnService.setSelectedIndex(1);             
                }else if(unUtilisateur.getIdservice()==3){
                    btnService.setSelectedIndex(2);             
                }else if(unUtilisateur.getIdservice()==4){
                    btnService.setSelectedIndex(3);             
                }else if(unUtilisateur.getIdservice()==5){
                    btnService.setSelectedIndex(4);             
                }
                //fonctionUser.setName(String.valueOf(unUtilisateur.getIdfonction()));
                message.setText(null);
            }
        } catch(NumberFormatException e) { 
            message.setText("Saisie incorrecte - format non respecté");
        } catch(NullPointerException e) {
            message.setText("Saisie incorrecte - format non respecté");
        } catch(SQLException ex) {
           message.setText("Erreur d'accès à la base de donnée");
        }
    }//GEN-LAST:event_btnValiderMouseClicked

    private void messageActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_messageActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_messageActionPerformed

    private void btnModifierMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnModifierMouseClicked
        int id = Integer.parseInt(idUser.getText());
        String mdp = mdpUser.getText();
        String email = emailUser.getText();
        int fonction = 0;
        int service = 0;
        String nomUser = nom.getText();
        if(fonctionUser.getSelectedIndex()==0){
                fonction = 1;   
            }else if(fonctionUser.getSelectedIndex()==1){
                fonction = 2;
            }else if(fonctionUser.getSelectedIndex()==2){
                fonction = 3;            
            }
        if(btnService.getSelectedIndex()==0){
            service = 1;
        }else if(btnService.getSelectedIndex()==1){
            service = 2;
        }else if(btnService.getSelectedIndex()==2){
            service = 3;            
        }else if(btnService.getSelectedIndex()==3){
            service = 4;            
        }else if(btnService.getSelectedIndex()==4){
            service = 5;            
        }
        Utilisateur unUtilisateur = null;
        try {
            unUtilisateur = Passerelle.donneUserId(id);
        } catch (SQLException ex) {
            Logger.getLogger(ModifierUser.class.getName()).log(Level.SEVERE, null, ex);
        }
        if(unUtilisateur == null){
            message.setText("L'utilisateur "+id+" n'existe pas");
        }else {          
            if(fonction == 1){
                Utilisateur unNouveauUtilisateur = new Utilisateur(id, nomUser, mdp, email, fonction, null);
                try {
                    if(Passerelle.modifierUser(unNouveauUtilisateur) == true){
                        message.setText("L'utilisateur "+id+" a été modifié");
                    }else{
                        message.setText("L'utilisateur "+id+" n'a pas été modifié");
                    }
                } catch (SQLException ex) {
                    Logger.getLogger(ModifierUser.class.getName()).log(Level.SEVERE, null, ex);
                }
            }else if(fonction == 2){
                Utilisateur unNouveauUtilisateur = new Utilisateur(id, nomUser, mdp, email, fonction,service);
                try {
                    if(Passerelle.modifierUser(unNouveauUtilisateur) == true){
                        message.setText("L'utilisateur "+id+" a été modifié");
                    }else if(btnService.getSelectedIndex()==-1){
                        message.setText("Veuillez choisir un service pour l'utilisateur n°"+id);                           
                    }else{
                        message.setText("L'utilisateur "+id+" n'a pas été modifié");
                    }
                } catch (SQLException ex) {
                    Logger.getLogger(ModifierUser.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
            
        } 
    }//GEN-LAST:event_btnModifierMouseClicked

    private void btnQuitterMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnQuitterMouseClicked
        dispose();
    }//GEN-LAST:event_btnQuitterMouseClicked

    private void fonctionUserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fonctionUserActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fonctionUserActionPerformed

    private void fonctionUserItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_fonctionUserItemStateChanged
        if(fonctionUser.getSelectedIndex()==0){
            btnService.setEnabled(false);
            btnService.setSelectedIndex(-1);
        }else if(fonctionUser.getSelectedIndex()==1){
            btnService.setEnabled(true);
        }else{
            btnService.setEnabled(false);
        }
    }//GEN-LAST:event_fonctionUserItemStateChanged

    private void fonctionUserMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_fonctionUserMouseClicked
        //JOptionPane.showMessageDialog(this, "L'item à changé");
        
    }//GEN-LAST:event_fonctionUserMouseClicked

    private void fonctionUserMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_fonctionUserMouseExited
        
    }//GEN-LAST:event_fonctionUserMouseExited

    private void fonctionUserMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_fonctionUserMouseReleased
        
    }//GEN-LAST:event_fonctionUserMouseReleased

    private void fonctionUserMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_fonctionUserMousePressed
       
    }//GEN-LAST:event_fonctionUserMousePressed

    private void fonctionUserMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_fonctionUserMouseEntered
        
    }//GEN-LAST:event_fonctionUserMouseEntered

    private void fonctionUserFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_fonctionUserFocusLost
        
    }//GEN-LAST:event_fonctionUserFocusLost

    private void fonctionUserPropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_fonctionUserPropertyChange
        // TODO add your handling code here:
    }//GEN-LAST:event_fonctionUserPropertyChange

    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnModifier;
    private javax.swing.JButton btnQuitter;
    private javax.swing.JComboBox<String> btnService;
    private javax.swing.JButton btnValider;
    private javax.swing.JTextField emailUser;
    private javax.swing.JComboBox<String> fonctionUser;
    private javax.swing.JTextField idUser;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabelService;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JTextField mdpUser;
    private javax.swing.JTextField message;
    private javax.swing.JTextField nom;
    // End of variables declaration//GEN-END:variables
}
